---

replicaCount: 1

image:
  registry: ghcr.io
  repository: edgecomllc
  name: eupf
  tag: ""

securityContext:
  privileged: true

volumes:
  - name: sys
    hostPath:
      path: /sys

volumeMounts:
  - name: sys
    mountPath: /sys
    readOnly:  true

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    endpoints:
      port: metrics
      path: "/metrics"

imagePullSecrets:
  - name: gh-container-registry

extraContainerPorts:
  - name: metrics
    containerPort: 9090
    protocol: tcp

service:
  type: ClusterIP
  port: 8080
  extraPorts:
    - port: 9090
      targetPort: metrics
      protocol: TCP
      name: metrics

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
