name: deploy by helm

on:
  workflow_call:
    inputs:
      helm_cmd_args:
        required: true
        type: string
      kube_context:
        required: true
        type: string
      environment_name:
        required: true
        type: string
    secrets:
      kube_config:
        required: true

jobs:

  deploy:
    runs-on: self-hosted
    env:
      HELM_DEPLOYMENT_NAMESPACE_NAME: free5gc
      HELM_CHART_RELEASE_NAME: eupf
      HELM_CHART_DIRECTORY: .deploy/helm/universal-chart
      HELM_CMD_ARGS: ${{ inputs.helm_cmd_args }}
    environment:
      name: ${{ inputs.environment_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          context: ${{ inputs.kube_context }}
          kubeconfig: ${{ secrets.kube_config }}

      - name: helm install
        run: |
          export SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`
          export IMAGE_TAG="sha-${SHORT_SHA}"
          sed -ie "s/appVersion.*$/appVersion\: \"$SHORT_SHA\"/g" ${HELM_CHART_DIRECTORY}/Chart.yaml
          helm upgrade --install ${HELM_CHART_RELEASE_NAME} ${HELM_CHART_DIRECTORY} --namespace ${HELM_DEPLOYMENT_NAMESPACE_NAME} ${HELM_CMD_ARGS} --set-string image.tag=${IMAGE_TAG}
