name: deploy to dev

on:
  push:
    branches:
      - "main"

jobs:

  use-build:
    uses: edgecomllc/eupf/.github/workflows/build.yml@main
  deploy:
    uses: edgecomllc/eupf/.github/workflows/deploy.yml@main
    name: deploy to dev
    needs: use-build
    with:
      kube_context: "edgecom-dev"
      environment_name: "dev"
      helm_cmd_args: "--wait --timeout 60s --values .deploy/helm/values/dev.yaml"
    secrets:
      kube_config: ${{ secrets.KUBE_CONFIG_DEV }}
